Repository ministryofjustice/cloud-platform-infrastructure, pull requests merged in 2019-02, with the labels that each got.

#149 Increase es-live storage and add dedicated masters
  terraform/global-resources/elasticsearch.tf
Labels: do-not-merge

#156 add inactive user check template
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/README.md
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/check_inactive_users.yaml
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/delete_users_in_suspendedusersgroup.py
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/disable_unused_credentials.py
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/slack_integration.py
  cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/package_template.sh
Labels: WIP

#124 Introduce cert-manager component
  terraform/cloud-platform-components/cert-manager.tf
  terraform/cloud-platform-components/external-dns.tf
  terraform/cloud-platform-components/kiam.tf
  terraform/cloud-platform-components/main.tf
  terraform/cloud-platform-components/nginx-ingress-acme.tf
  terraform/cloud-platform-components/nginx-ingress.tf
  terraform/cloud-platform-components/resources/cert-manager/letsencrypt-production.yaml
  terraform/cloud-platform-components/resources/cert-manager/letsencrypt-staging.yaml
  terraform/cloud-platform-components/resources/cert-manager/servicemonitor.yaml
  terraform/cloud-platform-components/resources/kiam/servicemonitor.yaml
  terraform/cloud-platform-components/resources/nginx-ingress/servicemonitor.yaml
  terraform/cloud-platform-components/templates/nginx-ingress/default-certificate.yaml
Labels: in progress
